- name: breaking change
  color: e3846d
  description: Changes that break existing functionality
  aliases: [breaking]

- name: bug
  color: d73a4a
  description: Something isn't working as expected
  aliases: [bugfix]

- name: build
  color: 1d7363
  description: Changes to the build system or dependencies

- name: chore
  color: d2d2d2
  description: Non-functional updates or maintenance tasks
  aliases: [maintenance, cleanup]

- name: ci
  color: 40f448
  description: Updates to CI workflows or scripts
  aliases: [github_actions]

- name: documentation
  color: 0075ca
  description: Improvements or additions to documentation
  aliases: [docs]

- name: duplicate
  color: 758f7c
  description: Issue or PR already exists

- name: example
  color: 07A287
  description: Sample code and demos

- name: external dependency
  color: e5f6ef
  description: Requires changes in an external dependency
  aliases: [dependencies]

- name: external help wanted
  color: '008672' # needs to be a string
  description: Looking for help on this ticket from the community
  aliases: [help wanted]

- name: feature
  color: 14caec
  description: A new feature or request
  aliases: [enhancement]

- name: good first issue
  color: 7057ff
  description: Suitable for new contributors

- name: has repro steps
  color: 3799b8
  description: Includes steps to reproduce the issue

- name: invalid
  color: e4e669
  description: Not applicable or incorrect

- name: investigating
  color: ce37f8
  description: Under investigation for cause or scope

- name: needs repro steps
  color: '910578' # needs to be a string
  description:  Lacks steps to reproduce the issue

- name: needs triage
  color: '000000' # needs to be a string
  description: Pending categorization or prioritization

- name: p0
  color: ff0000
  description: Critical-priority issue such as a build break or regression

- name: p1
  color: '990000' # needs to be a string
  description: High-priority issue

- name: p2
  color: '884242' # needs to be a string
  description: Medium-priority issue

- name: p3
  color: '664242' # needs to be a string
  description: Low-priority issue

- name: performance
  color: f9d0c4
  description: Changes that improve performance

- name: refactor
  color: e29a12
  description: Code changes without new features or fixes

- name: release
  color: 0075ca
  description: Release preparation and versioning tasks

- name: revert
  color: d4c5f9
  description: Reverts a previous commit

- name: skip health check
  color: '75e221' # needs to be a string
  description: Skips the "Health" check for the PR

- name: style
  color: df76c7
  description: Code formatting or styling changes

- name: test
  color: 4f0fb9
  description: Changes that add missing tests or correcting existing tests
  aliases: [tests]

- name: tool
  color: 0031D6
  description: Updates internal tooling

- name: waiting for response
  color: c68654
  description: Pending further feedback
  aliases: [waiting for feedback]

- name: won't fix
  color: ffffff
  description: Will not be addressed
  aliases: [wontfix, out of scope]
