- name: automation
  color: '4310DE'
  description: Replace handcrafted code that doesn't scale 

- name: blocked
  color: '241B02'
  description: Waiting on an external issue to be resolved

- name: breaking change
  color: 'ff0000'
  description: Changes that break existing functionality
  aliases: [breaking]

- name: bug
  color: 'e63946'
  description: Something isn't working as expected
  aliases: [bugfix]

- name: build
  color: '228B22'
  description: Changes to the build system or dependencies

- name: chore
  color: 'b0b0b0'
  description: Non-functional updates or maintenance tasks
  aliases: [maintenance, cleanup]

- name: ci
  color: '32CD32'
  description: Updates to CI workflows or scripts
  aliases: [github_actions]

- name: documentation
  color: '4682B4'
  description: Improvements or additions to documentation
  aliases: [docs]

- name: duplicate
  color: 'a9a9a9'
  description: Issue or PR already exists

- name: epic
  color: '640AAC'
  description: A theme of work that contain sub-tasks

- name: example
  color: '20b2aa'
  description: Sample code and demos

- name: external dependency
  color: '8a2be2'
  description: Requires changes in an external dependency
  aliases: [dependencies]

- name: external help wanted
  color: '00ced1'
  description: Looking for help on this ticket from the community
  aliases: [help wanted]

- name: feature
  color: '14caec'
  description: A new feature or request
  aliases: [enhancement]

- name: good first issue
  color: '9370db'
  description: Suitable for new contributors

- name: has repro steps
  color: '4682B4'
  description: Includes steps to reproduce the issue

- name: invalid
  color: 'f4a460'
  description: Not applicable or incorrect

- name: investigating
  color: 'ff6347'
  description: Under investigation for cause or scope

- name: needs repro steps
  color: 'e9967a'
  description: Lacks steps to reproduce the issue

- name: needs triage
  color: '696969'
  description: Pending categorization or prioritization

- name: P0
  color: 'ff0000'
  description: Critical-priority issue such as a build break or regression

- name: P1
  color: '990000'
  description: High-priority issue

- name: P2
  color: '770000'
  description: Medium-priority issue

- name: P3
  color: '550000'
  description: Low-priority issue

- name: performance
  color: 'ffb6c1'
  description: Changes that improve performance

- name: refactor
  color: 'ffa07a'
  description: Code changes without new features or fixes

- name: release
  color: '4169e1'
  description: Release preparation and versioning tasks

- name: revert
  color: 'd4c5f9'
  description: Reverts a previous commit

- name: style
  color: 'da70d6'
  description: Code formatting or styling changes

- name: test
  color: '4b0082'
  description: Changes that add missing tests or correcting existing tests
  aliases: [tests]

- name: tool
  color: '2e8b57'
  description: Updates internal tooling

- name: waiting for response
  color: 'c68654'
  description: Pending further feedback
  aliases: [waiting for feedback]

- name: won't fix
  color: '696969'
  description: Will not be addressed
  aliases: [wontfix, out of scope]
