name: next_version
description: A package that determines the next project version by analyzing
  conventional commits.
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  conventional_commit: ^0.6.0+1
  version: ^3.0.2

dev_dependencies:
  checks: ^0.3.0
  lints: ^5.0.0
  test: ^1.25.8
