name: next_version
description: A package that helps you to determine the next version of your
  package based on the commits in your repository.
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  conventional_commit: ^0.6.0+1
  meta: ^1.16.0
  version: ^3.0.2

dev_dependencies:
  checks: ^0.3.0
  lints: ^5.0.0
  test: ^1.25.8
