name: API Documentation Workflow

on:
  workflow_call:
    inputs:
      dart_sdk:
        required: false
        type: string
        default: 'stable'
      runs_on:
        required: false
        type: string
        default: 'ubuntu-latest'
      use_flutter:
        required: false
        type: boolean
        default: false
      working_directory:
        required: false
        type: string
        default: '.'

jobs:
  build:
    defaults:
      run:
        working-directory: ${{ inputs.working_directory }}

    runs-on: ${{ inputs.runs_on }}

    steps:
      - name: 📚 Git Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - name: 🎯 Setup Dart
        uses: dart-lang/setup-dart@6afc89df92d6eb3834022f73cd65adc8cdfcb92d
        with:
          sdk: ${{ inputs.dart_sdk }}

      - name: 🐦 Setup Flutter
        if: ${{ inputs.use_flutter }}
        uses: subosito/flutter-action@1a449444c387b1966244ae4d4f8c696479add0b2
        with:
          cache: true
          cache-key: flutter-${{ runner.os }}-${{ hashFiles('**/pubspec.lock') }}

      - name: 📒 Check API Documentation
        run: dart doc --dry-run
