name: Dart Release Workflow

on:
  workflow_call:
    inputs:
      dart_sdk:
        required: false
        type: string
        default: stable
      dry_run:
        required: false
        type: boolean
        default: false
      runs_on:
        required: false
        type: string
        default: ubuntu-latest
      timeout_minutes:
        required: false
        type: number
        default: 5
      working_directory:
        required: false
        type: string
        default: '.'
    secrets:
      token:
        required: true

jobs:
  publish:
    defaults:
      run:
        working-directory: ${{ inputs.working_directory }}

    runs-on: ${{ inputs.runs_on }}

    timeout-minutes: ${{ inputs.timeout_minutes }}

    steps:
      - name: 📚 Git Checkout
        uses: actions/checkout@v6

      - name: 🎯 Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ inputs.dart_sdk }}

      - name: 📦 Install Dependencies
        run: dart pub get

      - name: 🌵 Dry Run
        run: dart pub publish --dry-run

      - name: ⬇️ Download extract_latest_changelog.dart
        run: curl -fLo extract_latest_changelog.dart https://raw.githubusercontent.com/halildurmus/tools/main/tools/extract_latest_changelog.dart

      - name: 🔍 Extract Package Metadata
        id: extract_package_metadata
        run: |
          name=$(grep '^name:' pubspec.yaml | head -n 1 | awk '{print $2}')
          version=$(grep '^version:' pubspec.yaml | head -n 1 | awk '{print $2}')

          echo "📦 Package: $name"
          echo "🚀 Version: $version"

          echo "name=$name" >> $GITHUB_OUTPUT
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: 🔍 Extract Changelog
        run: |
          dart run extract_latest_changelog.dart
          echo "📝 Changelog:"
          cat changelog.txt

      - name: 🚀 Create GitHub Release
        if: ${{ !inputs.dry_run }}
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.token }}
          commit: main
          tag: '${{ steps.extract_package_metadata.outputs.name }}-v${{ steps.extract_package_metadata.outputs.version }}'
          name: 'package:${{ steps.extract_package_metadata.outputs.name }} v${{ steps.extract_package_metadata.outputs.version }}'
          bodyFile: ${{ inputs.working_directory }}/changelog.txt
          draft: false
          prerelease: false
