name: Pana Workflow

on:
  workflow_call:
    inputs:
      min_score:
        required: false
        type: number
        default: 160
      pana_version:
        required: false
        type: string
      working_directory:
        required: false
        type: string
        default: '.'

jobs:
  build:
    defaults:
      run:
        working-directory: ${{ inputs.working_directory }}

    runs-on: ubuntu-latest

    steps:
      - name: 📚 Git Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0

      - name: 🐦 Setup Flutter
        uses: subosito/flutter-action@1a449444c387b1966244ae4d4f8c696479add0b2
        with:
          cache: true
          cache-key: flutter-${{ runner.os }}-${{ hashFiles('**/pubspec.lock') }}

      - name: 📦 Install Pana
        run: flutter pub global activate pana ${{ inputs.pana_version }}

      - name: 📦 Install webp
        run: sudo apt-get -y install webp

      - name: 📊 Verify Pana Score
        run: |
          pana --no-warning --json \
          --exit-code-threshold=$(( 160 - ${{ inputs.min_score }} ))
