name: Semantic PR Workflow

on:
  workflow_call:
    inputs:
      types:
        required: false
        type: string
      scopes:
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 🤖 Ensure Commit is Semantic
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: ${{ inputs.types }}
          scopes: ${{ inputs.scopes }}
          validateSingleCommit: false
          wip: false
